### ISSUE TITLE
ELFlash ArrayIndexOutOfBoundsException on invalid Cookie value

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#4547]
From: https://github.com/javaserverfaces/mojarra/issues/4386

This can easily reproduced by sending a csfcfc cooke with value `7aXBAow%3D`

**Comment by codylerum** [comment]
@arjantijms should I port in the version from 2.4 here as well? It appears the encrypt and decrypt methods in https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/util/ByteArrayGuardAESCTR.java have been simplified.

**Comment by jasonex7** [comment]
This is fixed with PR #4668

**Comment by didiez** [comment]
We are using `2.3.14` and the bug is still there. 
Are there any plans to release another version in the `2.3` branch? The bugfix seems backported to `2.3` in 7144ebcd43ad963dd594ea584ec1d9b98b6f3848

**Comment by manorrock** [comment]
Please fix on 3.0 and master as well

**Comment by melloware** [comment]
This looks like it was already ported to 3.0 and 4.0 and can be closed.
