### ISSUE TITLE
Wrong behaviour UIInput's component

### ISSUE THREAD

**Issue by samsonovav** [eclipse-ee4j/mojarra#4704]
After upgrading to wildfly 19.1.0 my projects don't work as expected.
I localized problem in javax.faces.component.UIInput from jboss-jsf-api_2.3_spec 3.0.0.SP02 in validate(FacesContext context) method. When the context parameter javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to true then the value from UIInput component is not set to null any more. Moreover, the setter method on backing bean is not called in this case.
Link for discuss here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wildfly/99Lb8HASSyw/FX_rlFKsBAAJ

**Comment by erickdeoliveiraleal** [comment]
#4550

**Comment by erickdeoliveiraleal** [comment]
@soul2zimate

**Comment by soul2zimate** [comment]
This seems related to previous mentioned fix, I will be looking for an alternative fix for the original issue. A temporary workaround is not enabling the parameter  `javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL` to trigger this unexpected behavior for the moment.

**Comment by Hurz** [comment]
The fix was integrated into Wildfly 20.0.0. The fix has caused a new misbehaviour: When rendering a composit component with a facet containing a required input field, its validation triggers even though the field isn't rendered.

I've attached a reproducer. Open /web-application/index.xhtml and push the button. On WF20.0.0 an unhandled validation message appears in the logfile. This is not the case in WF20.0.0.Beta1 or earlier, before this fix was introduced.
[DemoValidationBug.zip](https://github.com/eclipse-ee4j/mojarra/files/4837478/DemoValidationBug.zip)

**Comment by soul2zimate** [comment]
It's the same issue as described in https://github.com/eclipse-ee4j/mojarra/issues/4716, it was fixed in https://issues.redhat.com/browse/WFLY-13497

**Comment by erickdeoliveiraleal** [comment]
WildFly 20.0.1 fixed it.

**Comment by erickdeoliveiraleal** [comment]
Looks like the issue is still there https://github.com/eclipse-ee4j/mojarra/issues/4734

**Comment by BalusC** [comment]
Fixed over there.
